// lib/destinations.js

export const DESTINATIONS = [
{
name: "New York City, NY",
country: "US",
lat: 40.7128,
lon: -74.006,
climate: "cool",
cost: "high",
tags: ["City Skylines", "Culture & History", "Food", "Fast-Paced"],
summary: "Iconic global city with endless attractions, dining, and culture."
},
{
name: "Los Angeles, CA",
country: "US",
lat: 34.0522,
lon: -118.2437,
climate: "warm",
cost: "high",
tags: ["Beach", "City Skylines", "Entertainment"],
summary: "Sprawling city with beaches, entertainment, and diverse neighborhoods."
},
{
name: "Chicago, IL",
country: "US",
lat: 41.8781,
lon: -87.6298,
climate: "cool",
cost: "medium",
tags: ["City Skylines", "Food", "Culture & History"],
summary: "Architectural landmark city with deep-dish pizza and lakefront views."
},
{
name: "Las Vegas, NV",
country: "US",
lat: 36.1699,
lon: -115.1398,
climate: "warm",
cost: "medium",
tags: ["Fast-Paced", "Entertainment", "Nightlife"],
summary: "High-energy destination famous for shows, dining, and nightlife."
},
{
name: "Miami, FL",
country: "US",
lat: 25.7617,
lon: -80.1918,
climate: "warm",
cost: "high",
tags: ["Beach", "Nightlife", "Warm & Sunny"],
summary: "Tropical city with beaches, nightlife, and Latin culture."
},
{
name: "San Francisco, CA",
country: "US",
lat: 37.7749,
lon: -122.4194,
climate: "cool",
cost: "high",
tags: ["City Skylines", "Culture & History", "Food"],
summary: "Historic coastal city known for landmarks and diverse neighborhoods."
},
{
name: "Seattle, WA",
country: "US",
lat: 47.6062,
lon: -122.3321,
climate: "cool",
cost: "medium",
tags: ["Nature Destinations", "City Skylines", "Food"],
summary: "Pacific Northwest city surrounded by water and mountains."
},
{
name: "Denver, CO",
country: "US",
lat: 39.7392,
lon: -104.9903,
climate: "cool",
cost: "medium",
tags: ["Outdoors", "Mountains", "Nature Destinations"],
summary: "Mile High City with easy access to the Rocky Mountains."
},
{
name: "Austin, TX",
country: "US",
lat: 30.2672,
lon: -97.7431,
climate: "warm",
cost: "medium",
tags: ["Food", "Music", "Culture"],
summary: "Lively Texas city known for music, food trucks, and festivals."
},

// 11–25
{
name: "New Orleans, LA",
country: "US",
lat: 29.9511,
lon: -90.0715,
climate: "warm",
cost: "medium",
tags: ["Food", "Culture & History", "Nightlife"],
summary: "Historic city famous for cuisine, music, and festivals."
},
{
name: "Boston, MA",
country: "US",
lat: 42.3601,
lon: -71.0589,
climate: "cool",
cost: "high",
tags: ["Culture & History", "City"],
summary: "Historic New England city with rich American history."
},
{
name: "San Diego, CA",
country: "US",
lat: 32.7157,
lon: -117.1611,
climate: "warm",
cost: "high",
tags: ["Beach", "Warm & Sunny", "Relaxing"],
summary: "Laid-back coastal city with beaches and sunshine."
},
{
name: "Portland, OR",
country: "US",
lat: 45.5051,
lon: -122.675,
climate: "cool",
cost: "medium",
tags: ["Food", "Nature Destinations", "Culture"],
summary: "Creative city surrounded by forests and rivers."
},
{
name: "Phoenix, AZ",
country: "US",
lat: 33.4484,
lon: -112.074,
climate: "warm",
cost: "medium",
tags: ["Warm & Sunny", "Desert", "Relaxing"],
summary: "Desert city known for sunshine and resorts."
},
{
name: "Dallas, TX",
country: "US",
lat: 32.7767,
lon: -96.797,
climate: "warm",
cost: "medium",
tags: ["City", "Food", "Culture"],
summary: "Major Texas metro with arts and dining."
},
{
name: "Atlanta, GA",
country: "US",
lat: 33.749,
lon: -84.388,
climate: "warm",
cost: "medium",
tags: ["Culture", "City", "Food"],
summary: "Southern city with rich history and modern culture."
},
{
name: "Minneapolis, MN",
country: "US",
lat: 44.9778,
lon: -93.265,
climate: "cold",
cost: "medium",
tags: ["City", "Culture", "Lakes"],
summary: "Twin Cities metro with parks and cultural attractions."
},
{
name: "Kansas City, MO",
country: "US",
lat: 39.0997,
lon: -94.5786,
climate: "cool",
cost: "low",
tags: ["Food", "Culture", "City"],
summary: "Known for BBQ, jazz, and Midwestern charm."
},
{
name: "Orlando, FL",
country: "US",
lat: 28.5383,
lon: -81.3792,
tags: ["Theme Park", "Family", "Warm & Sunny", "Fast-Paced & Exciting"],
climate: "warm",
cost: "medium",
summary: "Theme park capital with nonstop family attractions and entertainment.",
},
{
name: "Tampa, FL",
country: "US",
lat: 27.9506,
lon: -82.4572,
tags: ["Beach", "Relaxing", "Warm & Sunny"],
climate: "warm",
cost: "medium",
summary: "Gulf Coast city with beaches, sports, and waterfront dining.",
},
{
name: "St. Petersburg, FL",
country: "US",
lat: 27.7676,
lon: -82.6403,
tags: ["Beach", "Relaxing", "Culture & History"],
climate: "warm",
cost: "medium",
summary: "Art-focused beach city with a laid-back coastal vibe.",
},
{
name: "Key West, FL",
country: "US",
lat: 24.5551,
lon: -81.7800,
tags: ["Beach", "Relaxing", "Warm & Sunny"],
climate: "warm",
cost: "high",
summary: "Island escape known for sunsets, snorkeling, and island culture.",
},
{
name: "Savannah, GA",
country: "US",
lat: 32.0809,
lon: -81.0912,
tags: ["Culture & History", "Relaxing"],
climate: "warm",
cost: "medium",
summary: "Historic southern city with charm, food, and walkable squares.",
},
{
name: "Charleston, SC",
country: "US",
lat: 32.7765,
lon: -79.9311,
tags: ["Culture & History", "Relaxing"],
climate: "warm",
cost: "medium",
summary: "Elegant coastal city with historic architecture and cuisine.",
},
{
name: "Asheville, NC",
country: "US",
lat: 35.5951,
lon: -82.5515,
tags: ["Outdoors", "Relaxing", "Culture & History"],
climate: "cool",
cost: "medium",
summary: "Mountain town with hiking, breweries, and artsy energy.",
},
{
name: "Nashville, TN",
country: "US",
lat: 36.1627,
lon: -86.7816,
tags: ["City", "Fast-Paced & Exciting", "Culture & History"],
climate: "warm",
cost: "medium",
summary: "Music capital with nightlife, food, and Southern culture.",
},
{
name: "Memphis, TN",
country: "US",
lat: 35.1495,
lon: -90.0490,
tags: ["Culture & History", "City"],
climate: "warm",
cost: "low",
summary: "Historic music city known for blues, BBQ, and civil rights history.",
},
{
name: "Louisville, KY",
country: "US",
lat: 38.2527,
lon: -85.7585,
tags: ["Culture & History", "Relaxing"],
climate: "cool",
cost: "low",
summary: "River city famous for bourbon, horses, and walkable neighborhoods.",
},
{
name: "Cincinnati, OH",
country: "US",
lat: 39.1031,
lon: -84.5120,
tags: ["City", "Culture & History"],
climate: "cool",
cost: "low",
summary: "Historic Midwest city with sports, food, and riverfront views.",
},
{
name: "Columbus, OH",
country: "US",
lat: 39.9612,
lon: -82.9988,
tags: ["City", "A Mix of Both"],
climate: "cool",
cost: "low",
summary: "Growing city with neighborhoods, food, and family attractions.",
},
{
name: "Cleveland, OH",
country: "US",
lat: 41.4993,
lon: -81.6944,
tags: ["City", "Culture & History"],
climate: "cold",
cost: "low",
summary: "Lakefront city with museums, sports, and music history.",
},
{
name: "Detroit, MI",
country: "US",
lat: 42.3314,
lon: -83.0458,
tags: ["City", "Culture & History"],
climate: "cold",
cost: "low",
summary: "Revitalized city with arts, food, and industrial heritage.",
},
{
name: "Milwaukee, WI",
country: "US",
lat: 43.0389,
lon: -87.9065,
tags: ["City", "Relaxing"],
climate: "cold",
cost: "low",
summary: "Lake Michigan city with breweries, festivals, and waterfront parks.",
},
{
name: "Madison, WI",
country: "US",
lat: 43.0731,
lon: -89.4012,
tags: ["Relaxing", "Outdoors"],
climate: "cold",
cost: "low",
summary: "College town with lakes, trails, and a relaxed pace.",
},
{
name: "St. Paul, MN",
country: "US",
lat: 44.9537,
lon: -93.0900,
tags: ["Culture & History", "Relaxing"],
climate: "cold",
cost: "medium",
summary: "Historic twin city with museums and riverfront charm.",
},
{
name: "St. Louis, MO",
country: "US",
lat: 38.6270,
lon: -90.1994,
tags: ["City", "Culture & History"],
climate: "cool",
cost: "low",
summary: "Gateway city with free attractions and historic neighborhoods.",
},
{
name: "Omaha, NE",
country: "US",
lat: 41.2565,
lon: -95.9345,
tags: ["City", "Relaxing"],
climate: "cool",
cost: "low",
summary: "Friendly Midwest city with food, zoo, and riverfront areas.",
},
{
name: "Des Moines, IA",
country: "US",
lat: 41.5868,
lon: -93.6250,
tags: ["Relaxing", "City"],
climate: "cold",
cost: "low",
summary: "Small city with arts, food scene, and walkable downtown.",
},
{
name: "Fargo, ND",
country: "US",
lat: 46.8772,
lon: -96.7898,
tags: ["Relaxing", "Culture & History"],
climate: "cold",
cost: "low",
summary: "Quirky northern city with unique culture and small-town charm.",
},
{
name: "Sioux Falls, SD",
country: "US",
lat: 43.5446,
lon: -96.7311,
tags: ["Outdoors", "Relaxing"],
climate: "cold",
cost: "low",
summary: "Compact city with parks, waterfalls, and easy pace.",
},
{
name: "Boulder, CO",
country: "US",
lat: 40.01499,
lon: -105.2705,
tags: ["Outdoors", "Relaxing"],
climate: "cool",
cost: "high",
summary: "Active college town with hiking, views, and wellness culture.",
},
{
name: "Colorado Springs, CO",
country: "US",
lat: 38.8339,
lon: -104.8214,
tags: ["Outdoors", "Relaxing"],
climate: "cool",
cost: "medium",
summary: "Scenic city near Pikes Peak with parks and family attractions.",
},
{
name: "Scottsdale, AZ",
country: "US",
lat: 33.4942,
lon: -111.9261,
tags: ["Relaxing", "Warm & Sunny"],
climate: "warm",
cost: "high",
summary: "Upscale desert escape with spas, dining, and nightlife.",
},
{
name: "Sedona, AZ",
country: "US",
lat: 34.8697,
lon: -111.7609,
tags: ["Outdoors", "Relaxing"],
climate: "cool",
cost: "high",
summary: "Red rock destination known for hiking and scenic beauty.",
},
{
name: "Las Vegas, NV",
country: "US",
lat: 36.1699,
lon: -115.1398,
tags: ["Fast-Paced & Exciting", "City"],
climate: "warm",
cost: "medium",
summary: "Entertainment capital with shows, dining, and nightlife.",
},
{
name: "Reno, NV",
country: "US",
lat: 39.5296,
lon: -119.8138,
tags: ["City", "Outdoors"],
climate: "cool",
cost: "low",
summary: "Smaller Nevada city with outdoor access and casinos.",
},
{
name: "Salt Lake City, UT",
country: "US",
lat: 40.7608,
lon: -111.8910,
tags: ["Outdoors", "City"],
climate: "cold",
cost: "medium",
summary: "Mountain city with skiing, hiking, and cultural sites.",
},
{
name: "Park City, UT",
country: "US",
lat: 40.6461,
lon: -111.4980,
tags: ["Outdoors", "Relaxing"],
climate: "cold",
cost: "high",
summary: "Resort town known for skiing, festivals, and mountain charm.",
},
{
name: "Boise, ID",
country: "US",
lat: 43.6150,
lon: -116.2023,
tags: ["Outdoors", "Relaxing"],
climate: "cool",
cost: "low",
summary: "Growing city with trails, river access, and relaxed pace.",
},
{
name: "Spokane, WA",
country: "US",
lat: 47.6588,
lon: -117.4260,
tags: ["Outdoors", "Relaxing"],
climate: "cool",
cost: "low",
summary: "Inland Northwest city with parks, waterfalls, and nature access.",
},
{
name: "Tacoma, WA",
country: "US",
lat: 47.2529,
lon: -122.4443,
tags: ["City", "Relaxing"],
climate: "cool",
cost: "medium",
summary: "Waterfront city near Seattle with museums and parks.",
},
{
name: "Bend, OR",
country: "US",
lat: 44.0582,
lon: -121.3153,
tags: ["Outdoors", "Relaxing"],
climate: "cool",
cost: "medium",
summary: "High desert town with breweries, trails, and mountain views.",
},
{
name: "San Jose, CA",
country: "US",
lat: 37.3382,
lon: -121.8863,
tags: ["City", "A Mix of Both"],
climate: "warm",
cost: "high",
summary: "Silicon Valley hub with culture, food, and tech history.",
},
{
name: "Santa Cruz, CA",
country: "US",
lat: 36.9741,
lon: -122.0308,
tags: ["Beach", "Relaxing"],
climate: "cool",
cost: "high",
summary: "Coastal city with surf culture and classic boardwalk.",
},
{
name: "Monterey, CA",
country: "US",
lat: 36.6002,
lon: -121.8947,
tags: ["Relaxing", "Culture & History"],
climate: "cool",
cost: "high",
summary: "Scenic coastal town with aquariums and ocean views.",
},
{
name: "Palm Springs, CA",
country: "US",
lat: 33.8303,
lon: -116.5453,
tags: ["Relaxing", "Warm & Sunny"],
climate: "warm",
cost: "high",
summary: "Desert resort city with pools, spas, and mid-century style.",
},
{
name: "Fresno, CA",
country: "US",
lat: 36.7378,
lon: -119.7871,
tags: ["City", "Relaxing"],
climate: "warm",
cost: "low",
summary: "Central California city near national parks and agriculture.",
},
{
name: "Bakersfield, CA",
country: "US",
lat: 35.3733,
lon: -119.0187,
tags: ["City", "Relaxing"],
climate: "warm",
cost: "low",
summary: "Inland California city with music history and road-trip appeal.",
},
{
name: "Riverside, CA",
country: "US",
lat: 33.9806,
lon: -117.3755,
tags: ["City", "A Mix of Both"],
climate: "warm",
cost: "medium",
summary: "Southern California metro near mountains and attractions.",
},
{
name: "San Bernardino, CA",
country: "US",
lat: 34.1083,
lon: -117.2898,
tags: ["City", "Outdoors"],
climate: "warm",
cost: "low",
summary: "Gateway city to mountain recreation and desert travel.",
},
{
name: "Oxnard, CA",
country: "US",
lat: 34.1975,
lon: -119.1771,
tags: ["Beach", "Relaxing"],
climate: "cool",
cost: "medium",
summary: "Coastal city with beaches and a laid-back vibe.",
},
{
name: "Paris, France",
country: "FR",
lat: 48.8566,
lon: 2.3522,
climate: "cool",
cost: "high",
tags: ["Culture & History", "Romantic", "Food"],
summary: "World-famous city of art, history, and cuisine."
},
{
name: "London, United Kingdom",
country: "GB",
lat: 51.5072,
lon: -0.1276,
climate: "cool",
cost: "high",
tags: ["Culture & History", "City", "Food"],
summary: "Historic capital blending tradition and modern life."
},
{
name: "Rome, Italy",
country: "IT",
lat: 41.9028,
lon: 12.4964,
climate: "warm",
cost: "medium",
tags: ["Culture & History", "Food"],
summary: "Ancient city filled with landmarks and cuisine."
},
{
name: "Barcelona, Spain",
country: "ES",
lat: 41.3851,
lon: 2.1734,
climate: "warm",
cost: "medium",
tags: ["Beach", "Culture", "Food"],
summary: "Vibrant city combining beach life and architecture."
},
{
name: "Amsterdam, Netherlands",
country: "NL",
lat: 52.3676,
lon: 4.9041,
climate: "cool",
cost: "medium",
tags: ["Culture", "City", "Relaxing"],
summary: "Canal-lined city known for art and bike culture."
},
{
name: "Tokyo, Japan",
country: "JP",
lat: 35.6762,
lon: 139.6503,
climate: "cool",
cost: "high",
tags: ["City Skylines", "Culture", "Food"],
summary: "Ultra-modern city blended with tradition."
},
{
name: "Kyoto, Japan",
country: "JP",
lat: 35.0116,
lon: 135.7681,
climate: "cool",
cost: "medium",
tags: ["Culture & History", "Relaxing"],
summary: "Historic Japanese city with temples and gardens."
},
{
name: "Cancún, Mexico",
country: "MX",
lat: 21.1619,
lon: -86.8515,
climate: "warm",
cost: "medium",
tags: ["Beach", "All-Inclusive", "Warm & Sunny"],
summary: "Popular beach destination with resorts and nightlife."
},
{
name: "Toronto, Canada",
country: "CA",
lat: 43.6532,
lon: -79.3832,
climate: "cool",
cost: "medium",
tags: ["City", "Culture", "Food"],
summary: "Diverse Canadian city with vibrant neighborhoods."
},
{
name: "Vancouver, Canada",
country: "CA",
lat: 49.2827,
lon: -123.1207,
climate: "cool",
cost: "high",
tags: ["Nature Destinations", "City"],
summary: "Coastal city surrounded by mountains and ocean."
},

// 11–25
{
name: "Dubai, UAE",
country: "AE",
lat: 25.2048,
lon: 55.2708,
climate: "warm",
cost: "high",
tags: ["Luxury", "City", "Warm & Sunny"],
summary: "Luxury-focused city with modern architecture."
},
{
name: "Bangkok, Thailand",
country: "TH",
lat: 13.7563,
lon: 100.5018,
climate: "warm",
cost: "low",
tags: ["Food", "Culture", "City"],
summary: "Bustling city known for street food and temples."
},
{
name: "Sydney, Australia",
country: "AU",
lat: -33.8688,
lon: 151.2093,
climate: "warm",
cost: "high",
tags: ["Beach", "City"],
summary: "Harbor city with iconic beaches and landmarks."
},
{
name: "Auckland, New Zealand",
country: "NZ",
lat: -36.8485,
lon: 174.7633,
climate: "cool",
cost: "medium",
tags: ["Nature Destinations", "City"],
summary: "Gateway city to New Zealand’s natural beauty."
},
{
name: "Reykjavik, Iceland",
country: "IS",
lat: 64.1466,
lon: -21.9426,
climate: "cold",
cost: "high",
tags: ["Nature Destinations", "Adventure"],
summary: "Base city for exploring Iceland’s landscapes."
}
];    